# Global properties
server:
  port: 8080
logging:
  level:
    root: info
ecommercepro:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://api.upthesky.net

# Metadata fetch and automatic database updating is disabled by default to allow the application to build without an active database connection. 
spring:
  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:30568/railway
    username: postgres
    password: 55da51DdCGfa1FFDeFFaFfF3e1a6aad3

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # temp:
        # Disable the metadata fetch
          # use_jdbc_metadata_defaults: false
    # Disable automatic database schema updating
    hibernate.ddl-auto: update
---
# Desktop profile
spring:
  config:
    activate:
      on-profile: desktop

  # Local database connection details
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: postgres
    password: postgres

---
# Prod profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://PGHOST:PGPORT/PGDATABASE
    username: PGUSER
    password: PGPASSWORD